apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-api
      tier: backend
  template:
    metadata:
      labels:
        app: gitops-api
        tier: backend
    spec:
      containers:
        - name: gitops-api
          image: docker-image-gitops-api
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 9080
          env:
            - name: PORT
              value: "9080"

---
apiVersion: v1
kind: Service
metadata:
  name: gitops-api
spec:
  selector:
    app: gitops-api
    tier: backend
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30036
      protocol: TCP