apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api.yml

images:
- name: docker-image-gitops-api # aponta para api.yml > Deployment > spec.template.spec.containers["gitops-api"].image
  newName: lucashccosta/poc-gitops-api
  newTag: newtag
