name: CD GitOps

on:
  push: 
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      
      - name: Use NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install ./api

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./api/Dockerfile
          context: ./api
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:${{ github.sha }}

      - name: Setup Kustomize.io
        uses: imranismail/setup-kustomize@v2

      - name: Update K8s Resources
        env: 
          DOCKER_REGISTRY_REPOSITORY: ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}
        run: |
          cd k8s
          kustomize edit set image docker-image-gitops-api=$DOCKER_REGISTRY_REPOSITORY:$GITHUB_SHA

      - name: Commit New Tag Version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "ci: set docker image version"

      - name: Commit Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: lucashccosta/poc-gitops